apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - image: matic4fri/rso-user-service:latest
          name: user
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://abul.db.elephantsql.com/igkywmox
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: igkywmox
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: 2_pNpLTnwT-R-CVW86Zdc1CCkj5demVV
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: user
