kumuluzee:
  name: user-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://104.45.79.50/users
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UserMetadataDS
      connection-url: jdbc:postgresql://rso-literatura.postgres.database.azure.com:5432/postgres
      username: posgres
      password: Rs0zap1ski
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UserMetadataDS
      http-health-check:
        connection-url: http://104.45.79.50/users/v1/users
  metrics:
    web-instrumentation:
      - name: users-endpoint
        url-pattern: /v1/users/*
  graphql:
    ui:
      mapping: /myGraphqlUsers
      enabled: true
rest-properties:
  maintenance-mode: false
  broken: false
